class Engine { constructor(t,e){this.t=t;this.e=e;this.tm=null} start(s){this.stop();this.rem=s;this.tot=s;this.tm=setInterval(()=>{this.rem--;this.t(this.rem,this.tot);if(this.rem<=0){this.stop();this.e()}},1000)} stop(){clearInterval(this.tm)} }

const Modules={
    activeEngine:null,
    Exam:{ eng:new Engine((r,t)=>{document.getElementById('exam-timer').innerText=Utils.format(r,r>3600);},()=>{alert('结束');View.toggleZen()}), start:()=>{Modules.stopAll();Modules.Exam.eng.start(document.getElementById('ex-dur').value*60);if(!document.body.classList.contains('zen-mode'))View.toggleZen();}, stop:()=>{Modules.Exam.eng.stop();View.toggleZen();} },
    Pomo:{ eng:new Engine((r,t)=>{document.getElementById('pomo-timer').innerText=Utils.format(r);},()=>{alert('完成')}), start:()=>{Modules.stopAll();Modules.Pomo.eng.start(25*60)}, reset:()=>{Modules.Pomo.eng.stop();document.getElementById('pomo-timer').innerText="25:00";} },
    Whiteboard:{ ctx:null,color:'#000',width:3,drawing:false,init:()=>{const c=document.getElementById('wb-canvas');Modules.Whiteboard.ctx=c.getContext('2d');c.width=c.offsetWidth;c.height=400;const s=e=>{Modules.Whiteboard.drawing=true;Modules.Whiteboard.draw(e)};const end=()=>{Modules.Whiteboard.drawing=false;Modules.Whiteboard.ctx.beginPath()};c.onmousedown=s;c.onmousemove=Modules.Whiteboard.draw;c.onmouseup=end;c.ontouchstart=e=>{s(e.touches[0]);e.preventDefault()};c.ontouchmove=e=>{Modules.Whiteboard.draw(e.touches[0]);e.preventDefault()};c.ontouchend=end},draw:e=>{if(!Modules.Whiteboard.drawing)return;const r=e.target.getBoundingClientRect();const x=(e.clientX||e.pageX)-r.left,y=(e.clientY||e.pageY)-r.top;const x_c=Modules.Whiteboard.ctx;x_c.lineWidth=Modules.Whiteboard.width;x_c.lineCap='round';x_c.strokeStyle=Modules.Whiteboard.color;x_c.lineTo(x,y);x_c.stroke();x_c.beginPath();x_c.moveTo(x,y)},clear:()=>{const c=document.getElementById('wb-canvas');Modules.Whiteboard.ctx.clearRect(0,0,c.width,c.height)}},
    Media:{ load:i=>{const f=i.files[0];if(f){document.getElementById('video-player').src=URL.createObjectURL(f);document.getElementById('media-container').classList.remove('hidden');document.querySelector('.media-drop-zone').style.display='none'}} },
    Countdown:{ eng:new Engine((r,t)=>{document.getElementById('cd-timer').innerText=Utils.format(r);},()=>{alert('时间到')}), start:()=>{Modules.stopAll();Modules.Countdown.eng.start(document.getElementById('cd-input').value*60)} },
    Stopwatch:{ t:0,tm:null,start:()=>{if(!Modules.Stopwatch.tm)Modules.Stopwatch.tm=setInterval(()=>{Modules.Stopwatch.t+=100;const d=new Date(Modules.Stopwatch.t);document.getElementById('sw-timer').innerText=`${Utils.pad(d.getUTCMinutes())}:${Utils.pad(d.getUTCSeconds())}.${Math.floor(d.getUTCMilliseconds()/10)}`},100)},pause:()=>{clearInterval(Modules.Stopwatch.tm);Modules.Stopwatch.tm=null},reset:()=>{Modules.Stopwatch.pause();Modules.Stopwatch.t=0;document.getElementById('sw-timer').innerText="00:00.00"} },
    Todo:{ r:()=>{document.getElementById('todo-list').innerHTML=Data.store.todos.map((t,i)=>`<div class="list-item"><span onclick="Data.store.todos[${i}].done=!Data.store.todos[${i}].done;Data.save('todos');Modules.Todo.r()" style="flex:1;text-decoration:${t.done?'line-through':'none'}">${t.txt}</span><button onclick="Data.store.todos.splice(${i},1);Data.save('todos');Modules.Todo.r()" style="background:transparent;border:none;">×</button></div>`).join('')}, add:()=>{const v=document.getElementById('todo-input').value;if(v){Data.store.todos.push({txt:v,done:false});Data.save('todos');Modules.Todo.r();document.getElementById('todo-input').value=''}}, render: function(){this.r()} },
    Schedule:{ r:()=>{document.getElementById('schedule-list').innerHTML=Data.store.schedule.map((s,i)=>`<div class="list-item"><span>${s}</span><button onclick="Data.store.schedule.splice(${i},1);Data.save('schedule');Modules.Schedule.r()" style="background:transparent;border:none;margin-left:auto;">×</button></div>`).join('')}, add:()=>{const v=prompt('内容');if(v){Data.store.schedule.push(v);Data.save('schedule');Modules.Schedule.r()}}, clear:()=>{Data.store.schedule=[];Data.save('schedule');Modules.Schedule.r()}, render: function(){this.r()} },
    Favs:{ r:()=>{document.getElementById('fav-list').innerHTML=Data.store.favs.map((f,i)=>`<div class="list-item"><a href="${f.url}" target="_blank" style="flex:1">${f.name}</a><button onclick="Data.store.favs.splice(${i},1);Data.save('favs');Modules.Favs.r()" style="background:transparent;border:none;">×</button></div>`).join('')}, add:()=>{const n=document.getElementById('fav-name').value,u=document.getElementById('fav-url').value;if(n&&u){Data.store.favs.push({name:n,url:u});Data.save('favs');Modules.Favs.r()}}, render: function(){this.r()} },
    Long:{ init:()=>{setInterval(()=>{['target','exam'].forEach(k=>{const d=Data.store.long[k];if(!d)return;const df=new Date(d)-new Date();const el=document.getElementById(k==='target'?'target-display':'exam-long-display');if(df<=0)el.innerText="DONE";else{const D=Math.floor(df/86400000),H=Math.floor((df%86400000)/3600000);el.innerText=`${D}天${H}时`}})},1000)}, set:k=>{Data.store.long[k]=document.getElementById(k==='target'?'target-input':'exam-long-input').value;localStorage.setItem(k==='target'?'targetDate':'examDate',Data.store.long[k])} },
    stopAll:()=>{if(Modules.activeEngine)Modules.activeEngine.stop();Modules.Stopwatch.pause()}
};